### ISSUE TITLE
New mountpoint for SERIALIZED_OBJECTS_DIR ?

### ISSUE THREAD

**Issue by loicdtx** [CONABIO/antares3-docker#1]
This is the directory where serialized objects get written.
Right now it's going `~/datacube_ingest/serialized_objects`. We should probably mount a separate directory for that...

**Comment by loicdtx** [comment]
Would also need another mountpoint to store processing output that are not reingested (e.g. The output of `model_predict.py`)

**Comment by palmoreck** [comment]
we could use another directory, LUSTRE is mounted so we can create a directory inside that. Also I saw that serialized_objects is mapped to:

```/LUSTRE/MADMEX/tasks/2018_tasks/datacube_madmex/datacube_directories_mapping_docker_2/datacube_ingest``` 

and inside that is serialized_objects:

```/LUSTRE/MADMEX/tasks/2018_tasks/datacube_madmex/datacube_directories_mapping_docker_2/datacube_ingest/serialized_objects/```
