### ISSUE TITLE
Missing python scripts for gdal

### ISSUE THREAD

**Issue by robmartz** [CONABIO/antares3-docker#7]
There are some functions missing in the gdal instalation for instance: gdal_calc.py, gdal_polygonize.py, gdal_fillnodata.py, gdal_merge.py, etc. In order to install them it is necesary to add `python-gdal` in the dependency installation step in Dockerfile.

**Comment by palmoreck** [comment]
`apt-get install python-gdal`

**Comment by palmoreck** [comment]
solved by https://github.com/CONABIO/antares3-docker/commit/f4183d13180e50f97728f30b2af5e94f243bb587
