### ISSUE TITLE
Install Sentinelsat

### ISSUE THREAD

**Issue by robmartz** [CONABIO/antares3-docker#8]
Install [sentinelsat](https://sentinelsat.readthedocs.io/en/stable/index.html) for local downloading of sentinel-2 images, even sentinel-1. Command to install `pip3.6 install --user sentinelsat`

**Comment by palmoreck** [comment]
solved by https://github.com/CONABIO/antares3-docker/commit/505ccb9cc17e0f627f175629200106b80dadef8a
